#!/usr/bin/env bash
# no-attribution — scans staged files for AI/tool attribution.
# Exits 1 on any match, blocking the commit.
# Invoked from .husky/pre-commit.

set -euo pipefail

PATTERN='claude|anthropic|ai[- ]generated|generated by|co-?authored-?by|openai|gpt-?[0-9]|copilot|cursor|codeium|windsurf|antigravity|assisted[- ]by'

# Staged files, name-only, excluding deletions
STAGED=$(git diff --cached --name-only --diff-filter=ACMR)

if [ -z "$STAGED" ]; then
  exit 0
fi

FINDINGS=""

while IFS= read -r FILE; do
  # Skip lockfiles and binaries
  case "$FILE" in
    pnpm-lock.yaml|package-lock.json|yarn.lock) continue ;;
    *.png|*.jpg|*.jpeg|*.webp|*.avif|*.gif|*.ico|*.pdf|*.zip) continue ;;
    *.woff|*.woff2|*.ttf|*.otf) continue ;;
  esac

  # Grep staged content (not working tree) to avoid missing staged-but-unsaved diffs
  if git show ":$FILE" 2>/dev/null | grep -niE "$PATTERN" > /tmp/no-attr-hits 2>/dev/null; then
    while IFS= read -r HIT; do
      FINDINGS="${FINDINGS}${FILE}:${HIT}\n"
    done < /tmp/no-attr-hits
  fi
done <<< "$STAGED"

rm -f /tmp/no-attr-hits

if [ -n "$FINDINGS" ]; then
  echo ""
  echo "commit blocked: attribution references found"
  echo ""
  printf "%b" "$FINDINGS"
  echo ""
  echo "Author is MNRV. Remove these references before committing."
  echo "See .claude/skills/no-attribution/SKILL.md"
  exit 1
fi

exit 0
