#!/usr/bin/env bash
# validate-commit-msg — enforces Conventional Commits and blocks AI attribution in messages.
# Invoked from .husky/commit-msg with the commit message file as $1.

set -euo pipefail

MSG_FILE="$1"
MSG=$(cat "$MSG_FILE")

# Strip comments (lines starting with #)
MSG_CLEAN=$(echo "$MSG" | grep -v '^#' || true)
SUBJECT=$(echo "$MSG_CLEAN" | head -n 1)

# --- 1. Reject attribution trailers and AI references ---
ATTR_PATTERN='claude|anthropic|ai[- ]generated|generated by|co-?authored-?by|openai|gpt-?[0-9]|copilot|cursor|codeium|windsurf|antigravity|assisted[- ]by|signed-off-by'

if echo "$MSG_CLEAN" | grep -niE "$ATTR_PATTERN" > /dev/null; then
  echo ""
  echo "commit blocked: attribution or AI reference in message"
  echo ""
  echo "$MSG_CLEAN" | grep -niE "$ATTR_PATTERN"
  echo ""
  echo "Author is MNRV. Remove the reference."
  exit 1
fi

# --- 2. Conventional Commits subject format ---
# Pattern: <type>(<scope>)?: <subject>
# Types: feat, fix, refactor, perf, test, docs, chore, build, ci
# Subject: lowercase start, no trailing period, ≤ 72 chars (whole subject line).

if [ ${#SUBJECT} -gt 72 ]; then
  echo "commit blocked: subject is ${#SUBJECT} chars, max is 72"
  echo "subject: $SUBJECT"
  exit 1
fi

CONV_RE='^(feat|fix|refactor|perf|test|docs|chore|build|ci)(\([a-z0-9-]+\))?: [a-z].+[^.]$'

if ! echo "$SUBJECT" | grep -qE "$CONV_RE"; then
  echo ""
  echo "commit blocked: subject does not match Conventional Commits"
  echo ""
  echo "  subject: $SUBJECT"
  echo ""
  echo "Expected: <type>(<scope>): <subject>"
  echo "  type:     feat | fix | refactor | perf | test | docs | chore | build | ci"
  echo "  scope:    optional, e.g. (storefront), (api), (prisma)"
  echo "  subject:  imperative, lowercase first letter, no trailing period"
  echo ""
  echo "Examples:"
  echo "  feat(storefront): add per-100g price to product card"
  echo "  fix(api): verify stripe signature before parsing event"
  echo "  chore(deps): pin next to 14.2.18"
  echo ""
  echo "See .claude/skills/commit-hygiene/SKILL.md"
  exit 1
fi

exit 0
